site_name: MarketData Analyzer Documentation
site_url: https://Cirrus04.github.io/MDappDoc/

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate

extra_css:
  - assets/custom.css

# Navigation Structure
nav:
  - 'Home': 'index.md'
  - 'Setup Guide':
    - 'Installation': 'guide/installation.md'
    - 'Configuration': 'guide/configuration.md'
    - 'Deployment': 'guide/deployment.md'
  - 'User Manual':
    - 'Web Interface': 'usage/web_interface.md'
    - 'Load Scripts': 'usage/shell_scripts.md'
  - 'Technical Analysis':
    - 'Indicators Overview': 'technical_analysis/indicators.md'
    - 'Bollinger Bands': 'technical_analysis/bollinger_bands.md'
    - 'RSI': 'technical_analysis/rsi.md'
    - 'ADX': 'technical_analysis/adx.md'
    - 'MACD': 'technical_analysis/macd.md'
  - 'Glossary':
    - 'Overview': 'glossary/overview.md'
    - 'EODHD': 'glossary/eodhd.md'
    - 'STRATO': 'glossary/strato.md'
    - 'VPS': 'glossary/vps.md'
    - 'MySQL': 'glossary/mysql.md'
    - 'Cron & Crontab': 'glossary/cron.md'
    - 'Bash Shell': 'glossary/bash_shell.md'
    - 'nano & vi': 'glossary/nano_vi.md'
    - 'Stop-Loss': 'glossary/stop_loss.md'
    - 'not yet translated': 'glossary/README.md'

  - 'Development':
    - 'Database Schema': 'development/database_schema.md'
    - 'SQL for Database Creation': 'development/database_create.md'
    - 'Data Sources': 'development/data_sources.md'
    - 'Maintenance': 'development/maintenance.md'
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list